
CREATE TABLE JOB(
   JOB_CODE CHAR(3) PRIMARY KEY,
   JOB_DESCRIPTION VARCHAR(15) NOT NULL,
   JOB_CHG_HOURS CHAR(2) NOT NULL,
   JOB_LAST_UPDATE DATE,

)

--Create table named EMP_1 which is a subset of EMPLOYEE table
CREATE TABLE EMP_1 (
   EMP_NUM   CHAR(3)  PRIMARY KEY,
   EMP_LNAME VARCHAR(15) NOT NULL,
   EMP_FNAME VARCHAR(15) NOT NULL,
   EMP_INITIAL CHAR(1),
   EMP_HIREDATE DATE,
   JOB_CODE CHAR(3),
   FOREIGN KEY (JOB_CODE)REFERENCES JOB );

CREATE TABLE PROJECT(
   PROJ_NUM CHAR(2) PRIMARY KEY,
   PROJ_NAME VARCHAR(20) NOT NULL,
   PROJ_VALUE CHAR(12),
   PROJ_BALANCE CHAR(12),
   EMP_NUM CHAR(3)
   FOREIGN KEY (EMP_NUM) REFERENCES EMP_1
  );

  --ASSIGNMENT TABLE
CREATE TABLE ASSIGNMENT(
    ASSIGN_NAME CHAR(4) PRIMARY KEY,
	ASSIGN DATE NOT NULL,
	PROJ_NUM CHAR(2) NOT NULL,
	EMP_NUM CHAR(3) NOT NULL,
	ASSIGN_JOB CHAR (3) NOT NULL,
	ASSIGN_HOURS CHAR(2),
  );
