


CREATE TABLE PROJECT(
   PROJ_NUM CHAR(2) PRIMARY KEY,
   PROJ_NAME VARCHAR(20) NOT NULL,
   PROJ_VALUE CHAR(12),
   PROJ_BALANCE CHAR(12),
   EMP_NUM CHAR(3)
   FOREIGN KEY (EMP_NUM) REFERENCES EMP_1
  );


