
CREATE TABLE JOB(
   JOB_CODE CHAR(3) PRIMARY KEY,
   JOB_DESCRIPTION VARCHAR(15) NOT NULL,
   JOB_CHG_HOURS CHAR(2) NOT NULL,
   JOB_LAST_UPDATE DATE,

)

--Create table named EMP_1 which is a subset of EMPLOYEE table
CREATE TABLE EMP_1 (
   EMP_NUM   CHAR(3)  PRIMARY KEY,
   EMP_LNAME VARCHAR(15) NOT NULL,
   EMP_FNAME VARCHAR(15) NOT NULL,
   EMP_INITIAL CHAR(1),
   EMP_HIREDATE DATE,
   JOB_CODE CHAR(3),
   FOREIGN KEY (JOB_CODE)REFERENCES JOB );

